"""added nullable=False in FK into MessageModel

Revision ID: 0521e351d622
Revises: 2959a0ef8b90
Create Date: 2021-10-19 18:56:33.828243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0521e351d622'
down_revision = '2959a0ef8b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'companyId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'companyId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
