"""Created summaries table

Revision ID: 0f9babdfe259
Revises: 38a5ae1ac0fc
Create Date: 2021-10-13 14:41:24.848568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9babdfe259'
down_revision = '38a5ae1ac0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(length=1023), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('speciality', sa.String(length=255), nullable=False),
    sa.Column('disponibility', sa.String(length=255), nullable=False),
    sa.Column('experience_time', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summaries')
    # ### end Alembic commands ###
