"""Created tech_skills table

Revision ID: 319ea70b5a80
Revises: 38a5ae1ac0fc
Create Date: 2021-10-15 10:16:42.050764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319ea70b5a80'
down_revision = '38a5ae1ac0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_skills')
    # ### end Alembic commands ###
