"""refactor snake_case to camel_case

Revision ID: 7cb0c756abae
Revises: fbd543843eb1
Create Date: 2021-10-19 09:33:03.510561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb0c756abae'
down_revision = 'fbd543843eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('companyName', sa.String(length=255), nullable=False))
    op.drop_column('companies', 'company_name')
    op.add_column('education', sa.Column('dateFrom', sa.Date(), nullable=True))
    op.add_column('education', sa.Column('dateTo', sa.Date(), nullable=True))
    op.drop_column('education', 'date_to')
    op.drop_column('education', 'date_from')
    op.add_column('experience', sa.Column('dateFrom', sa.Date(), nullable=True))
    op.add_column('experience', sa.Column('dateTo', sa.Date(), nullable=True))
    op.drop_column('experience', 'date_to')
    op.drop_column('experience', 'date_from')
    op.add_column('summaries', sa.Column('experienceTime', sa.Integer(), nullable=False))
    op.drop_column('summaries', 'experience_time')
    op.add_column('users', sa.Column('firstName', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('birthDate', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('linkedinProfile', sa.String(length=127), nullable=False))
    op.drop_column('users', 'linkedin_profile')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('linkedin_profile', sa.VARCHAR(length=127), autoincrement=False, nullable=False))
    op.drop_column('users', 'linkedinProfile')
    op.drop_column('users', 'birthDate')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.add_column('summaries', sa.Column('experience_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('summaries', 'experienceTime')
    op.add_column('experience', sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('experience', 'dateTo')
    op.drop_column('experience', 'dateFrom')
    op.add_column('education', sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('education', 'dateTo')
    op.drop_column('education', 'dateFrom')
    op.add_column('companies', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('companies', 'companyName')
    # ### end Alembic commands ###
