"""alter name tables education and experience

Revision ID: e2238e5d76c9
Revises: 7cb0c756abae
Create Date: 2021-10-19 09:36:02.222990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2238e5d76c9'
down_revision = '7cb0c756abae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('dateFrom', sa.Date(), nullable=True),
    sa.Column('dateTo', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('dateFrom', sa.Date(), nullable=True),
    sa.Column('dateTo', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('experience')
    op.drop_table('education')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('degree', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dateFrom', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dateTo', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='education_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='education_pkey')
    )
    op.create_table('experience',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dateFrom', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dateTo', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='experience_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='experience_pkey')
    )
    op.drop_table('experiences')
    op.drop_table('educations')
    # ### end Alembic commands ###
